- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - group_vars/localhost/vault.yml

  tasks:
    - name: Generate Terraform variables
      ansible.builtin.template:
        src: ../templates/secret.auto.tfvars.j2
        dest: ../terraform/secret.auto.tfvars
        mode: "0600"
      no_log: true

    - name: Generate Terraform backend config
      ansible.builtin.template:
        src: ../templates/secret.backend.tfbackend.j2
        dest: ../terraform/secret.backend.tfbackend
        mode: "0600"
      no_log: true
