- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Generate Terraform variables
      ansible.builtin.template:
        src: secret.auto.tfvars.j2
        dest: ../terraform/secret.auto.tfvars
        mode: "0600"
      no_log: true

    - name: Generate Terraform backend config
      ansible.builtin.template:
        src: secret.backend.tfbackend.j2
        dest: ../terraform/secret.backend.tfbackend
        mode: "0600"
      no_log: true
